// DragonStation Z-Level prototype.
// Copyright (c) pedel and OpenAI Codex.

using Robust.Shared.Configuration;

namespace Content.Shared.CCVar;

public sealed partial class CCVars
{
    /// <summary>
    /// Maximum number of resolved vertical boundaries cached by each process.
    /// </summary>
    public static readonly CVarDef<int> ZLevelBoundaryCacheCapacity =
        CVarDef.Create(
            "zlevel.boundary_cache_capacity",
            8192,
            CVar.REPLICATED | CVar.SERVER);

    /// <summary>
    /// Maximum world-Z distance considered by normal visibility and PVS.
    /// </summary>
    public static readonly CVarDef<int> ZLevelVisibilityMaxLevelDistance =
        CVarDef.Create(
            "zlevel.visibility_max_level_distance",
            4,
            CVar.REPLICATED | CVar.SERVER);

    /// <summary>
    /// Maximum cross-floor visibility checks performed for one session PVS refresh.
    /// </summary>
    public static readonly CVarDef<int> ZLevelPvsVisibilityCheckBudget =
        CVarDef.Create(
            "zlevel.pvs_visibility_check_budget",
            16384,
            CVar.SERVERONLY);

    /// <summary>
    /// Maximum adjacent world-Z boundaries resolved by one shared trace.
    /// </summary>
    public static readonly CVarDef<int> ZLevelTraceMaxVerticalCrossings =
        CVarDef.Create(
            "zlevel.trace_max_vertical_crossings",
            64,
            CVar.REPLICATED | CVar.SERVER);

    /// <summary>
    /// Maximum tile visits emitted by one shared trace.
    /// </summary>
    public static readonly CVarDef<int> ZLevelTraceMaxTileVisits =
        CVarDef.Create(
            "zlevel.trace_max_tile_visits",
            8_192,
            CVar.REPLICATED | CVar.SERVER);

    /// <summary>
    /// Maximum entity hits emitted by one shared trace.
    /// </summary>
    public static readonly CVarDef<int> ZLevelTraceMaxEntityHits =
        CVarDef.Create(
            "zlevel.trace_max_entity_hits",
            4_096,
            CVar.REPLICATED | CVar.SERVER);

    /// <summary>
    /// Maximum number of retained client aperture chunks used by vertical lighting and FOV.
    /// </summary>
    public static readonly CVarDef<int> ZLevelLightingApertureCacheCapacity =
        CVarDef.Create(
            "zlevel.lighting_aperture_cache_capacity",
            4_096,
            CVar.CLIENTONLY | CVar.ARCHIVE);

    /// <summary>
    /// Maximum native point-light tree entries inspected by vertical lighting per client frame.
    /// </summary>
    public static readonly CVarDef<int> ZLevelLightingMaxEmitterCandidatesPerFrame =
        CVarDef.Create(
            "zlevel.lighting_max_emitter_candidates_per_frame",
            4_096,
            CVar.CLIENTONLY | CVar.ARCHIVE);

    /// <summary>
    /// Maximum lower-floor point-light sources planned per client frame.
    /// </summary>
    public static readonly CVarDef<int> ZLevelLightingMaxEmittersPerFrame =
        CVarDef.Create(
            "zlevel.lighting_max_emitters_per_frame",
            256,
            CVar.CLIENTONLY | CVar.ARCHIVE);

    /// <summary>
    /// Maximum adjacent aperture layers composed by vertical lighting per client frame.
    /// </summary>
    public static readonly CVarDef<int> ZLevelLightingMaxApertureLayersPerFrame =
        CVarDef.Create(
            "zlevel.lighting_max_aperture_layers_per_frame",
            4_096,
            CVar.CLIENTONLY | CVar.ARCHIVE);

    /// <summary>
    /// Maximum cold aperture chunks built by vertical lighting per client frame.
    /// </summary>
    public static readonly CVarDef<int> ZLevelLightingMaxApertureBuildsPerFrame =
        CVarDef.Create(
            "zlevel.lighting_max_aperture_builds_per_frame",
            32,
            CVar.CLIENTONLY | CVar.ARCHIVE);

    /// <summary>
    /// Maximum aperture runs generated by vertical lighting per client frame.
    /// </summary>
    public static readonly CVarDef<int> ZLevelLightingMaxRunsPerFrame =
        CVarDef.Create(
            "zlevel.lighting_max_runs_per_frame",
            8_192,
            CVar.CLIENTONLY | CVar.ARCHIVE);

    /// <summary>
    /// Maximum lower-floor tile chunks composed per client frame.
    /// </summary>
    public static readonly CVarDef<int> ZLevelTileProjectionMaxChunksPerFrame =
        CVarDef.Create(
            "zlevel.tile_projection_max_chunks_per_frame",
            128,
            CVar.CLIENTONLY | CVar.ARCHIVE);

    /// <summary>
    /// Maximum adjacent aperture layers composed for lower-floor tiles per client frame.
    /// </summary>
    public static readonly CVarDef<int> ZLevelTileProjectionMaxApertureLayersPerFrame =
        CVarDef.Create(
            "zlevel.tile_projection_max_aperture_layers_per_frame",
            4_096,
            CVar.CLIENTONLY | CVar.ARCHIVE);

    /// <summary>
    /// Maximum cold aperture chunks built for lower-floor tiles per client frame.
    /// </summary>
    public static readonly CVarDef<int> ZLevelTileProjectionMaxApertureBuildsPerFrame =
        CVarDef.Create(
            "zlevel.tile_projection_max_aperture_builds_per_frame",
            32,
            CVar.CLIENTONLY | CVar.ARCHIVE);

    /// <summary>
    /// Maximum lower-floor tile slots inspected per client frame.
    /// </summary>
    public static readonly CVarDef<int> ZLevelTileProjectionMaxTileVisitsPerFrame =
        CVarDef.Create(
            "zlevel.tile_projection_max_tile_visits_per_frame",
            16_384,
            CVar.CLIENTONLY | CVar.ARCHIVE);

    /// <summary>
    /// Maximum adjacent mapping-preview chunks composed per client frame.
    /// </summary>
    public static readonly CVarDef<int> ZLevelMappingPreviewMaxChunksPerFrame =
        CVarDef.Create(
            "zlevel.mapping_preview_max_chunks_per_frame",
            128,
            CVar.CLIENTONLY | CVar.ARCHIVE);

    /// <summary>
    /// Maximum adjacent mapping-preview tile slots inspected per client frame.
    /// </summary>
    public static readonly CVarDef<int> ZLevelMappingPreviewMaxTileVisitsPerFrame =
        CVarDef.Create(
            "zlevel.mapping_preview_max_tile_visits_per_frame",
            16_384,
            CVar.CLIENTONLY | CVar.ARCHIVE);

    public static readonly CVarDef<bool> ZLevelDebugOverlay =
        CVarDef.Create("zlevel.debug_overlay", false, CVar.CLIENTONLY | CVar.ARCHIVE);
}
