// DragonStation Z-Level prototype.
// Copyright (c) pedel and OpenAI Codex.

using Content.Client.UserInterface.Controls;
using Content.Shared.ZLevel;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.ZLevel.UI;

[GenerateTypedNameReferences]
public sealed partial class ZLevelElevatorWindow : FancyWindow
{
    private readonly IGameTiming _timing;
    private ZLevelElevatorBoundUserInterfaceState? _state;

    public event Action<int>? RequestFloor;

    public ZLevelElevatorWindow()
    {
        RobustXamlLoader.Load(this);
        _timing = IoCManager.Resolve<IGameTiming>();
    }

    public void UpdateState(ZLevelElevatorBoundUserInterfaceState state)
    {
        _state = state;
        FloorContainer.RemoveAllChildren();

        StatusLabel.Text = state.State switch
        {
            ZLevelElevatorState.Idle when state.CurrentFloor is { } current =>
                Loc.GetString("zlevel-elevator-status-idle", ("z", current)),
            ZLevelElevatorState.Moving when state.TargetFloor is { } target =>
                Loc.GetString("zlevel-elevator-status-moving", ("z", target)),
            ZLevelElevatorState.Unpowered => Loc.GetString("zlevel-elevator-status-unpowered"),
            _ => Loc.GetString("zlevel-elevator-status-invalid"),
        };
        StatusLabel.SetOnlyStyleClass(state.State switch
        {
            ZLevelElevatorState.Idle => "positive",
            ZLevelElevatorState.Moving => "highlight",
            _ => "negative",
        });

        TravelProgress.Visible = state.State == ZLevelElevatorState.Moving &&
                                 state.TravelDuration > TimeSpan.Zero;
        UpdateProgress();

        if (state.ControlMode == ZLevelElevatorControlMode.Landing)
        {
            AddLandingButton(state);
            return;
        }

        foreach (var stop in state.Stops)
            AddCabinFloorButton(state, stop);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateProgress();
    }

    private void AddLandingButton(ZLevelElevatorBoundUserInterfaceState state)
    {
        var here = state.CurrentFloor == state.ControlFloor;
        var button = new Button
        {
            Text = here
                ? Loc.GetString("zlevel-elevator-button-here")
                : Loc.GetString("zlevel-elevator-button-call"),
            Disabled = here || state.State is not ZLevelElevatorState.Idle,
            HorizontalExpand = true,
            MinHeight = 40,
        };
        button.OnPressed += _ => RequestFloor?.Invoke(state.ControlFloor);
        FloorContainer.AddChild(button);
    }

    private void AddCabinFloorButton(
        ZLevelElevatorBoundUserInterfaceState state,
        ZLevelElevatorStopData stop)
    {
        var current = state.CurrentFloor == stop.LocalZ;
        var target = state.TargetFloor == stop.LocalZ;
        var button = new Button
        {
            Text = current
                ? Loc.GetString("zlevel-elevator-button-current", ("floor", stop.Label))
                : target
                    ? Loc.GetString("zlevel-elevator-button-target", ("floor", stop.Label))
                    : stop.Label,
            Disabled = current || state.State is not ZLevelElevatorState.Idle,
            HorizontalExpand = true,
            MinHeight = 36,
            Margin = new Thickness(0, 0, 0, 4),
        };
        button.OnPressed += _ => RequestFloor?.Invoke(stop.LocalZ);
        FloorContainer.AddChild(button);
    }

    private void UpdateProgress()
    {
        if (_state is not { State: ZLevelElevatorState.Moving } state ||
            state.TravelDuration <= TimeSpan.Zero)
        {
            TravelProgress.Value = 0f;
            return;
        }

        var remaining = state.ArrivalTime - _timing.CurTime;
        TravelProgress.Value = Math.Clamp(
            1f - (float) (remaining.TotalSeconds / state.TravelDuration.TotalSeconds),
            0f,
            1f);
    }
}
